# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apphosting/client/admin_jobs_v3/entity_set_spec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5apphosting/client/admin_jobs_v3/entity_set_spec.proto\x12\x1f\x61pphosting.client.admin_jobs_v3\"\x85\x03\n\rEntitySetSpec\x12J\n\tkind_type\x18\x01 \x01(\x0e\x32\x37.apphosting.client.admin_jobs_v3.EntitySetSpec.KindType\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12T\n\x0enamespace_type\x18\x03 \x01(\x0e\x32<.apphosting.client.admin_jobs_v3.EntitySetSpec.NamespaceType\x12\x11\n\tnamespace\x18\x04 \x01(\t\"B\n\x08KindType\x12\x19\n\x15KIND_TYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08ONE_KIND\x10\x01\x12\r\n\tALL_KINDS\x10\x02\"m\n\rNamespaceType\x12\x1e\n\x1aNAMESPACE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x44\x45\x46\x41ULT_NAMESPACE\x10\x01\x12\x11\n\rONE_NAMESPACE\x10\x02\x12\x12\n\x0e\x41LL_NAMESPACES\x10\x03\x42@\n(com.google.apphosting.client.adminjobsv3B\x12\x45ntitySetSpecProtoP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apphosting.client.admin_jobs_v3.entity_set_spec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.google.apphosting.client.adminjobsv3B\022EntitySetSpecProtoP\001'
  _globals['_ENTITYSETSPEC']._serialized_start=91
  _globals['_ENTITYSETSPEC']._serialized_end=480
  _globals['_ENTITYSETSPEC_KINDTYPE']._serialized_start=303
  _globals['_ENTITYSETSPEC_KINDTYPE']._serialized_end=369
  _globals['_ENTITYSETSPEC_NAMESPACETYPE']._serialized_start=371
  _globals['_ENTITYSETSPEC_NAMESPACETYPE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
